server:
  port: 8080

spring:
  datasource:
    username: root
    password: 253199
    url: jdbc:mysql://123.56.115.93:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml

# 多数据源路由配置
mini-db-router:
  jdbc:
    datasource:
      dbCount: 2
      tbCount: 4
      default: db00
      routerKey: uId
      list: db01,db02
      db00:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.115.93:3306/lottery?useUnicode=true
        username: root
        password: 253199
      db01:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.115.93:3306/lottery_01?useUnicode=true
        username: root
        password: 253199
      db02:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://123.56.115.93:3306/lottery_02?useUnicode=true
        username: root
        password: 253199
