server:
  port: 8080

spring:
  datasource:
    username: root
    password: 253199
    url: jdbc:mysql://123.56.115.93:3306/lottery?useUnicode=true
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml


